#+TITLE: braindump4000: heavily modified jethrokuan braindump

Convert your nested org mode database with broken links into a Hugo website.

In addition to nesting and broken links, braindump4000 also deals with it if
you are already using Hugo to publish parts of your org mode database.

You could also use org-publish (mine is setup), but on my 1000+ file database,
that takes forever, even when most of the files don't have to be republished.

* Quickstart

Let's say the root directory containing your nested org-mode database is
=~/notes/pkb4000= and you want a Hugo version in =~/notes/pkb4000-web= then you
could do the following:

** Create the hugo website

#+begin_src shell
  cd ~/notes
  hugo new site pkb4000-web
#+end_src

Install jethrokuan's [[https://github.com/jethrokuan/cortex][cortex]] theme:

#+begin_src shell
  cd ~/notes/pkb4000-web/themes
  git clone https://github.com/jethrokuan/cortex.git
#+end_src

Install his [[https://github.com/jethrokuan/braindump/blob/master/config.toml][config.toml]] at the top-level.

Add the root level of the config, add:

#+begin_src yaml
refLinksErrorLevel = "WARNING"
#+end_src

** Add two important pages

Create =pkb4000-web/content/_index.md= for the front page:

#+begin_src markdown
Well hello!

See the [index](posts).
#+end_src

Very importantly, create an empty =pkb4000-web/search/_index.md= just so that your search works.

** Build your site with braindump4000

#+begin_src shell
  cd notes/pkb4000
  git clone https://github.com/cpbotha/braindump4000.git
  cd notes
  hugo new site pkb4000-web
  cd notes/pkb4000/braindump4000
  python3 build.py
#+end_src






